name: Trigger a workflow using workflow_run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-workflow-run:
    runs-on: ubuntu-latest

    steps:
    
    - name: Git checkout
      uses: actions/checkout@v4
    
    # This is an optional step
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.WDC_APP_ID }}
        private-key: ${{ secrets.WDC_PVT_KEY }}


    - name: echo stmnts
      run: echo "i am a cat"

    - name: println
      run: echo "testing out workflow run on main branch to trigger worklfow named Build"

      
    - name: complete
      run: echo "Hello world"